# Generated by Django 5.1.3 on 2024-11-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untold_story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data',
        ),
        migrations.RemoveField(
            model_name='data',
            name='username',
        ),
        migrations.AddField(
            model_name='data',
            name='common_id',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='metadata',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='user_name',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='web_browser',
            field=models.TextField(default=None, null=True),
        ),
    ]
