# Generated by Django 5.1.3 on 2024-11-26 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('untold_story', '0002_remove_data_data_remove_data_username_data_common_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='metadata',
        ),
        migrations.AddField(
            model_name='data',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='filename',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='password_field',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='password_strength',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='user_name_field',
            field=models.TextField(default=None, null=True),
        ),
    ]
